AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Deploy a t3.micro EC2 instance in us-east-1 with Grafana and Prometheus installed via UserData on Ubuntu.

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the EC2 instance

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for the EC2 instance

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0866a3c8686eaeeba # Ubuntu Server 20.04 LTS AMI ID for us-east-1

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Grafana and Prometheus
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # SSH access
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0  # Grafana port
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0  # Prometheus port

  GrafanaPrometheusInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref SubnetId
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update system
          apt-get update -y
          apt-get upgrade -y

          # Install necessary packages
          apt-get install -y wget curl gnupg2 software-properties-common

          # Install Prometheus
          useradd --no-create-home --shell /bin/false prometheus
          mkdir /etc/prometheus
          mkdir /var/lib/prometheus
          chown prometheus:prometheus /etc/prometheus
          chown prometheus:prometheus /var/lib/prometheus
          cd /tmp
          LATEST_PROMETHEUS=$(curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep browser_download_url | grep linux-amd64.tar.gz | cut -d '"' -f 4)
          wget $LATEST_PROMETHEUS
          tar xvf prometheus*.tar.gz
          cd prometheus*/
          cp prometheus /usr/local/bin/
          cp promtool /usr/local/bin/
          chown prometheus:prometheus /usr/local/bin/prometheus
          chown prometheus:prometheus /usr/local/bin/promtool
          cp -r consoles /etc/prometheus
          cp -r console_libraries /etc/prometheus
          chown -R prometheus:prometheus /etc/prometheus/consoles
          chown -R prometheus:prometheus /etc/prometheus/console_libraries
          cat <<EOF > /etc/prometheus/prometheus.yml
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
          EOF
          chown prometheus:prometheus /etc/prometheus/prometheus.yml
          cat <<EOF > /etc/systemd/system/prometheus.service
          [Unit]
          Description=Prometheus Service
          After=network.target
          [Service]
          User=prometheus
          ExecStart=/usr/local/bin/prometheus \
            --config.file /etc/prometheus/prometheus.yml \
            --storage.tsdb.path /var/lib/prometheus/
          [Install]
          WantedBy=multi-user.target
          EOF
          systemctl daemon-reload
          systemctl start prometheus
          systemctl enable prometheus

          # Install Grafana
          wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
          add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
          apt-get update -y
          apt-get install -y grafana
          systemctl start grafana-server
          systemctl enable grafana-server.service

Outputs:
  InstancePublicIP:
    Description: Public IP address of the Grafana and Prometheus EC2 instance
    Value: !GetAtt GrafanaPrometheusInstance.PublicIp

  GrafanaURL:
    Description: URL to access Grafana
    Value: !Sub 'http://${GrafanaPrometheusInstance.PublicDnsName}:3000'

  PrometheusURL:
    Description: URL to access Prometheus
    Value: !Sub 'http://${GrafanaPrometheusInstance.PublicDnsName}:9090'